[tool.poetry]
name = "pymod6"
version = "0.1.0-dev"
description = ""
authors = ["Brian Schubert <schubert.b@northeastern.edu>"]
readme = "README.md"
packages = [
    { from = "src", include = "pymod6" },
]

[tool.poetry.dependencies]
python = "^3.9"
typing-extensions = "^4.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
