"""
Input file construction and handling.
"""

from . import basecases
from ._builder import CaseHandle, ModtranInputBuilder
from ._json import (
    Aerosol,
    AerosolCloud,
    AerosolHaze,
    AerosolSeason,
    AerosolStratospheric,
    Atmosphere,
    AtmosphereModel,
    AtmosphereProfile,
    AtmosphereProfileType,
    AtmosphereProfileUnits,
    Case,
    FileOptions,
    Geometry,
    JSONInput,
    JSONPrintOpt,
    ModtranInput,
    ModtranStatus,
    RTAlgorithm,
    RTExecutionMode,
    RTMultipleScattering,
    RTOptions,
    Spectral,
    Surface,
    SurfaceBRDFModel,
    SurfaceLambertianModel,
    SurfaceParam,
    SurfaceType,
)

__all__ = [
    "CaseHandle",
    "ModtranInputBuilder",
    "Aerosol",
    "AerosolCloud",
    "AerosolHaze",
    "AerosolSeason",
    "AerosolStratospheric",
    "Atmosphere",
    "AtmosphereModel",
    "AtmosphereProfile",
    "AtmosphereProfileType",
    "AtmosphereProfileUnits",
    "Case",
    "FileOptions",
    "Geometry",
    "JSONInput",
    "JSONPrintOpt",
    "ModtranInput",
    "ModtranStatus",
    "RTAlgorithm",
    "RTExecutionMode",
    "RTMultipleScattering",
    "RTOptions",
    "Spectral",
    "Surface",
    "SurfaceBRDFModel",
    "SurfaceLambertianModel",
    "SurfaceParam",
    "SurfaceType",
    "basecases",
]
